-- CREATE TABLE IF NOT EXISTS CLIENTE (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     NOME VARCHAR(100)
-- );

-- CREATE TABLE PRODUTO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     DESCRICAO VARCHAR(100),
--     PRECO_UNITARIO NUMERIC(20,2)
-- );

-- CREATE TABLE PEDIDO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
--     DATA_PEDIDO TIMESTAMP,
--     TOTAL NUMERIC(20,2)
-- );

-- CREATE TABLE ITEM_PEDIDO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
--     PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
--     QUANTIDADE INTEGER
-- );


CREATE TABLE IF NOT EXISTS customer (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100)
);

CREATE TABLE order (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    description VARCHAR(100),
    unit_price NUMERIC(20,2)
);

CREATE TABLE order (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    customer_id INTEGER REFERENCES customer (id),
    data_order TIMESTAMP,
    total NUMERIC(20,2)
);

CREATE TABLE item_order (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    order_id INTEGER REFERENCES order (id),
    order_id INTEGER REFERENCES order (id),
    amount INTEGER
);